version: '2'
services:
    oauthtest-app:
        image: oauthtest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://oauthtest-mysql:3306/oauthtest?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    oauthtest-mysql:
        extends:
            file: mysql.yml
            service: oauthtest-mysql
